import type { Metadata } from "next";
import "./globals.css";
import { Syne } from 'next/font/google'

const syne = Syne({ subsets: ['latin'], weight: '400', })

export const metadata: Metadata = {
  title: "Best Space Challenge",
  description: "Generated by Andresa",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={syne.className}>{children}</body>
    </html>
  );
}
